name: CI

on: [push,pull_request]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -el {0}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ["3.8", "3.9"]

    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      # Setup env
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: plassembler
          environment-file: build/environment.yaml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          miniforge-variant: Mambaforge
          channels: conda-forge,bioconda,defaults
          channel-priority: strict
          auto-update-conda: true
      - name: Install project
        shell: bash -l {0}
        run: |
          mamba install python=${{ matrix.python-version }}
          python -m pip install --upgrade pip
          pip install -e .
          pip install black
          pip install isort
          pip install pytest
          pip install pytest-cov
          pip install git+https://github.com/rrwick/Unicycler.git
          unicycler --help
      - name: Check formatting
        shell: bash -l {0}
        run: just check-fmt
      - name: Test and generate coverage report with pytest
        shell: bash -l {0}
        # need to set TERM to linux for some reason,kept getting a nasty error that was breaking unicycler 
        # https://github.com/cypress-io/cypress/issues/15679
        run: |
          export TERM=linux
          unicycler --version
          just test-ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      

